# NAVER 한달살기 - topic modeling

 참조사이트
 - https://hyemin-kim.github.io/2020/08/29/E-Python-TextMining-2/

In [1]:
# !pip install matplotlib seaborn sklearn konlpy scikit-learn wordcloud pyLDAvis gensim

import pandas as pd

import re


from konlpy.tag import Okt
okt = Okt() 
from collections import Counter

In [2]:
df = pd.read_csv('./data/naver_month.csv')
df

,title,contents,time,blog_text,key
0,돌아기랑 제주도한달살기 24일째(406일) : 비양도,첨에 제주도 한달살기 올때도 어디갈지 생각을 안하고 와서 매번 전날이나 아침에 오늘...,2023.11.27,첨에 제주도 한달살기 올때도 어디갈지 생각을 안하고 와서 매번 전날이나 아침에 오늘...,한달살기
1,"제주도 한달살기 (20) - 우도 코코나라, 문빵구, 돌담집, 몬딱...",한달살기 중 두번째 우도 ㅎㅎ 처음은 전기차를 빌렸지만 이번엔 카트형식으로 나란히 ...,2023.11.07,한달살기 중 두번째 우도 ㅎㅎ처음은 전기차를 빌렸지만 이번엔 카트형식으로 나란히 앉...,한달살기
2,제주동쪽숙소 제주도한달살기하기 좋은 구좌 제주오션뷰2차♪,#제주오션뷰2차 #제주도펜션 #제주동쪽숙소 제주에는 크게 동쪽과 서쪽으로 나뉘면서 ...,2023.12.13,#제주오션뷰2차#제주도펜션#제주동쪽숙소제주에는 크게 동쪽과 서쪽으로 나뉘면서 다양한...,한달살기
3,제주도 한달살기 비용 (한달살이 생활비),제주도 한달살기는 돈이 적게 들지는 않지만 우리 가족에게 꽤 많은 추억을 남겼으므로...,2022.02.23,"2021년 4월에 제주도 한달살기를 하고 왔다.세식구 기준(어른 둘, 아기 하나)으...",한달살기
4,제주도 한달살기 숙소 비용 제주 중문 애견동반 더맨션 이이공공,그중에서도 제일 마음에 들었던 건 오후 시간 깊숙이 들어오는 가을 햇살 창밖에 보이...,2023.10.14,이번에는 좀 여유로운 여행을 하고 싶어서다소 긴 일정으로 제주도에 방문했어요.여행...,한달살기
...,...,...,...,...,...
1932,제주도한달살이,드뎌 육지다~ 뒤로 보이는 육지가 제주항이네요. 3다도인 제주에 좋은 추억도 많이 ...,2020.12.18,#제주도 #제주한달살이#실버크클라우드코로나19로 발이묶인 윈드서퍼들의차선택은~~ 한...,한달살이
1933,[제주도 한달살이] 제주도 게스트하우스 스텝 후기...,"연돈 예약 성공해서 연돈도 먹고, 한라산 등산도 가고, 스쿠버다이빙도 배우고, 저녁...",2023.05.28,22년12월28일~23년2월4일약 한달동안 제주살이를 했다.(글 마지막에 스텝 꿀팁...,한달살이
1934,제주도 한달살이 시작!!!,무계획으로 출발 하는 제주도 한달살이!!! 퇴사를 하고 나니 새로운 환경에서 살아보...,2022.03.16,무계획으로 출발 하는 제주도 한달살이!!!퇴사를 하고 나니 새로운 환경에서 살아보고...,한달살이
1935,[제주도 한달살이 이야기] 평산제면소에서 마제소바먹고 러닝후...,제주도에선 술 잘 안먹겠다고 다짐했는데 거의 하루 한캔은 아니여도 한모금씩은 매일 ...,2022.02.20,오늘은 숙소 근처에 있다는 마제소바 집에 들렸어요맛집이라고 해서 저번에 왔었는데그때...,한달살이
1936,제주도 한달살이 day 1,친구가 제주도 한달살이 하러 간다고해서 백수몬인 나도 쫄래쫄래 쫓아가서 2주 있으려...,2022.06.11,친구가 제주도 한달살이 하러 간다고해서백수몬인 나도 쫄래쫄래 쫓아가서2주 있으려다 ...,한달살이

In [3]:
# df 수집 오류 결과 확인
(df == 'error').sum()

title        0
contents     0
time         0
blog_text    0
key          0
dtype: int64

In [4]:
df.isnull().sum()
# blog_text가 nan인 행 존재 -> 제외

title        0
contents     0
time         0
blog_text    3
key          0
dtype: int64

In [5]:
df[df['blog_text'].isna() == 1]

,title,contents,time,blog_text,key
1807,제주도 한달살이 스물한번째 날,제주도 한달살이 스물한번째 날입니다 오늘은 제주도에 오후부터 비가 예보 되있어서 나...,2022.03.30,NaN,한달살이
1882,제주도 한달살이 스물여덟번째 날,제주도 한달살이 스물여덟번째 날입니다 이제 제주도 살이 삼일 남았습니다 이번주는 날...,2022.04.07,NaN,한달살이
1919,제주도 한달살이 열다섯번째 날,제주도 한달살이 열다섯번째 날 입니다 벌써 한달중 절반이 지나가는군요 아침에 일어나...,2022.03.24,NaN,한달살이

In [6]:
# blog_text가 nan인 겨우 제외
df = df[df['blog_text'].isna() != 1]

### 토픽모델링
https://velog.io/@mare-solis/LDA-%ED%86%A0%ED%94%BD-%EB%AA%A8%EB%8D%B8%EB%A7%81%EC%9C%BC%EB%A1%9C-%EC%BD%98%ED%85%90%EC%B8%A0-%EB%A6%AC%EB%B7%B0%EB%A5%BC-%EB%B6%84%EC%84%9D%ED%95%98%EC%9E%90

In [7]:
# def text_cleaning(x):
#     nous = okt.nouns(hangul_function(x))
#     nous = [x for x in nous if len(x) > 1]  # 한글자 키워드 제거    
#     nous = [word for word in nous if not word in stopwords]
#     return nous

# temp_list = []
# for blog in df['blog_text']:    
#     temp_list.append(text_cleaning(blog))

In [8]:
def hangul_function(text):
    hangul = re.compile('[^ ㄱ-ㅣ 가-힣]')  # 한글 추출 규칙: 띄어 쓰기(1 개)를 포함한 한글
    result = hangul.sub('', text)  # 위에 설정한 "hangul"규칙을 "text"에 적용(.sub)시킴
    return result

In [9]:
from gensim.models.ldamodel import LdaModel
from gensim.models.callbacks import CoherenceMetric
from gensim import corpora
from gensim.models.callbacks import PerplexityMetric


import pickle
import pyLDAvis.gensim_models as gensimvis
import pyLDAvis
from gensim.models.coherencemodel import CoherenceModel
import matplotlib.pyplot as plt

In [10]:
stopwords = set([])

web_stopwords = pd.read_csv("https://raw.githubusercontent.com/yoonkt200/FastCampusDataset/master/korean_stopwords.txt").values.tolist()
web_stopwords[:10]

for i in web_stopwords:
    stopwords.add(i[0])

print(len(stopwords))

jeju_stopwords = [ '리뷰', '숙소', '정말', '동안', '다음', '바로', '근처', '조금', '시간',
                   '호스트', '정도', '방문', '사장', '이용', '다시', '예약', '살이', '살기', '아주', '추천', '하루', '이번',
                   '처음', '달동', '저희', '하나', '사용', '모두', '진짜', '일주일', '보름', '선택', '시작', '한번', '가장', '마음',
                   '제외', '이동', '무엇', '준비', '그냥', '감사',  '덕분', '후기', '기회',  '다른', '여기', '우리',
                   '미스터', '미스터멘션', '멘션', '때문', '오늘', '도착', '보고', '마지막', '가지', '이제', '지금', '모습', '위해',
                   '타고', '사실', '포스팅', '주문', '역시', '침대', '거실', '매일', '출발', '소개', '기억', '참고', '계속', '객실',
                   '일차', '이야기', '요즘', '이유', '경우', '일단', '거의', '스텝', '제일', '자주', '어디', '마무리', '아래', '운영',
                   '이상', '의자', '별로', '원래', '중간', '뭔가', '첫째', '체크', '잠시', '언제', '살짝', '해도', '계단', '부분', '냉장고',
                   '침실', '기본', '제공', '일찍', '인테리어', '완전', '추가', '등등', '매우', '가야', '그때', '기간', '마치', '가득', '대부분',
                   '미리', '둘째', '근무', '공간', '스테이', '알파', '엄마', '아빠', '아들', '일정', '계획', '아침', '주방', '서울', '육지',
                   '점심', '저녁', '자리', '두리', '언니', '가격', '건물', '숙박', '만원', '가기', '코로나' ,                   
                   '호텔', '펜션', '게스트하우스', '독채','화장실', '욕실', '숙박', '세탁기', '가면', '직접', '비용', '길이',
                    '여행', '트립', '제주', '제주도', '생각', '느낌',
                    '광고', '스텝', '블로그', '개월', '도서관', '스탭'
                   ]
for word in jeju_stopwords:
    stopwords.add(word)

print(len(stopwords))

594
739

### 토픽 모델링 완성

In [11]:
temp_list = []


for blog in df['blog_text']:
    # 한글만 남기고, okt를 통해서 명사만 남기는
    LDA_nous = okt.nouns(hangul_function(blog))
    # 2글자 이상의 명사만 남겨서
    LDA_nous = [x for x in LDA_nous if len(x) > 1]  # 한글자 키워드 제거    
    # 불용어 제거
    LDA_nous = [word for word in LDA_nous if not word in stopwords]
    # temp_list에 사용할 명사들만 남긴다.
    temp_list.append(LDA_nous)

## 사용할 명사들을 사전화
dictionary = corpora.Dictionary(temp_list)

# 2개 이상의 문서에 나오고, 50% 이상의 문서에 나오는 경우 제외
dictionary.filter_extremes(no_below=2, no_above=0.5)

# 해당 단어들을 말뭉치로 만들어라
corpus_LDA = [dictionary.doc2bow(text) for text in temp_list]

## 이코드의 의미는 모르겠지만.. ## 빼면 안돌아간다.
temp = dictionary[0]


num_topics = 5 
chunksize = 2000 
passes = 20 
iterations = 400 
eval_every = None # 모델 성능을 평가하는 간격


id2word = dictionary.id2token 

model = LdaModel(
    corpus=corpus_LDA, # 분석에 사용할 말뭉치
    id2word=id2word, # id2word는 단어의 ID와 단어를 매핑하는 딕셔너리
    chunksize=chunksize, # 모델 학습 시 사용되는 문서의 묶음 크기
    alpha='auto',
    eta='auto',
    iterations=iterations,
    num_topics=num_topics, # 토픽 그룹의 갯수를 정해줘
    passes=passes, # 전체 코퍼스를 몇 번 반복하여 학습
    eval_every=eval_every # iteration 횟수
)

lda_visualization = gensimvis.prepare(model, corpus_LDA, dictionary, sort_topics=True)
pyLDAvis.save_html(lda_visualization, './result/topicmodeling_complete.html')

In [12]:
model.get_document_topics(corpus_LDA)

In [13]:
# 집단별 단어 빈도수
from pprint import pprint
pprint(model.print_topics())

[(0,
  '0.011*"바다" + 0.010*"사람" + 0.006*"친구" + 0.005*"가족" + 0.005*"벚꽃" + 0.005*"카페" '
  '+ 0.004*"거리" + 0.004*"해변" + 0.004*"생활" + 0.004*"날씨"'),
 (1,
  '0.017*"오름" + 0.015*"코스" + 0.012*"올레길" + 0.010*"사람" + 0.007*"한라산" + '
  '0.006*"숲길" + 0.005*"마을" + 0.005*"풍경" + 0.005*"캠프" + 0.004*"정상"'),
 (2,
  '0.009*"하우스" + 0.008*"위치" + 0.006*"가족" + 0.005*"서귀포" + 0.005*"시설" + '
  '0.005*"바다" + 0.005*"거리" + 0.004*"마당" + 0.004*"감성" + 0.004*"분위기"'),
 (3,
  '0.015*"카페" + 0.011*"바다" + 0.010*"사람" + 0.006*"날씨" + 0.006*"체험" + '
  '0.005*"해수욕장" + 0.005*"구경" + 0.004*"친구" + 0.004*"우도" + 0.003*"바람"'),
 (4,
  '0.015*"맛집" + 0.014*"카페" + 0.008*"바다" + 0.008*"아기" + 0.007*"식당" + 0.006*"메뉴" '
  '+ 0.005*"사람" + 0.004*"돼지" + 0.004*"해변" + 0.004*"커피"')]

In [14]:
top_topics = model.top_topics(corpus_LDA)
top_topics

[([(0.015160247, '맛집'),
   (0.013514234, '카페'),
   (0.008143415, '바다'),
   (0.00782284, '아기'),
   (0.006860537, '식당'),
   (0.005806196, '메뉴'),
   (0.004532959, '사람'),
   (0.004462665, '돼지'),
   (0.004381956, '해변'),
   (0.0039979024, '커피'),
   (0.003917966, '애월'),
   (0.003868753, '서귀포'),
   (0.0037319597, '해수욕장'),
   (0.003650208, '가족'),
   (0.0035783183, '위치'),
   (0.0035232257, '음식'),
   (0.003452948, '칼국수'),
   (0.0033902784, '전복'),
   (0.0032577247, '바람'),
   (0.0032399478, '주차장')],
  -1.667538551043053),
 ([(0.017473347, '오름'),
   (0.015308348, '코스'),
   (0.012031718, '올레길'),
   (0.009560184, '사람'),
   (0.007035185, '한라산'),
   (0.005773244, '숲길'),
   (0.0050093043, '마을'),
   (0.0049544307, '풍경'),
   (0.004905106, '캠프'),
   (0.0042123124, '정상'),
   (0.0038352355, '겨울'),
   (0.0035315522, '걷기'),
   (0.0034288361, '식사'),
   (0.0033638703, '바다'),
   (0.0033582097, '사려'),
   (0.0033447628, '올레'),
   (0.0033435742, '해변'),
   (0.003272243, '버스'),
   (0.003267819, '둘레길'),
   (0.0032384875, '나무')],
  -1.698734366700705),
 ([(0.015044305, '카페'),
   (0.011088425, '바다'),
   (0.010433327, '사람'),
   (0.006373038, '날씨'),
   (0.005515511, '체험'),
   (0.0049265996, '해수욕장'),
   (0.004696184, '구경'),
   (0.004004708, '친구'),
   (0.0039984616, '우도'),
   (0.003354284, '바람'),
   (0.0032112196, '커피'),
   (0.0030991668, '비행기'),
   (0.0030004357, '산책'),
   (0.002906156, '노을'),
   (0.0027766924, '공항'),
   (0.0027105568, '맛집'),
   (0.0025044754, '남편'),
   (0.0024683748, '함덕'),
   (0.0024520217, '주차'),
   (0.002379647, '기록')],
  -1.7352049228874917),
 ([(0.011180566, '바다'),
   (0.009738998, '사람'),
   (0.0063769394, '친구'),
   (0.0051034214, '가족'),
   (0.0047974223, '벚꽃'),
   (0.0047779717, '카페'),
   (0.004290761, '거리'),
   (0.0041313316, '해변'),
   (0.0039883447, '생활'),
   (0.0037949192, '날씨'),
   (0.0035247141, '풍경'),
   (0.003305284, '요리'),
   (0.0030666387, '위치'),
   (0.0030464276, '우동'),
   (0.003039948, '분위기'),
   (0.0029921622, '게스트'),
   (0.0028946747, '손님'),
   (0.0028001524, '마당'),
   (0.0027998353, '식사'),
   (0.0027978693, '고기')],
  -1.8528494601017524),
 ([(0.0093182605, '하우스'),
   (0.008316321, '위치'),
   (0.005785477, '가족'),
   (0.005334788, '서귀포'),
   (0.0053282636, '시설'),
   (0.005209361, '바다'),
   (0.0047216937, '거리'),
   (0.004484927, '마당'),
   (0.003929376, '감성'),
   (0.0035557684, '분위기'),
   (0.0034455664, '쉐어'),
   (0.0034152826, '테라스'),
   (0.0032330353, '테이블'),
   (0.0031899628, '주차'),
   (0.0030589327, '빨래'),
   (0.0029270072, '애월'),
   (0.0029252616, '힐링'),
   (0.002911793, '내부'),
   (0.002905933, '주변'),
   (0.0028916395, '민박')],
  -1.9482858649298922)]

In [15]:
avg_topic_coherence = sum([t[1] for t in top_topics]) / num_topics
print('Average topic coherence: %.4f.' % avg_topic_coherence)

from pprint import pprint
pprint(top_topics)

Average topic coherence: -1.7805.
[([(0.015160247, '맛집'),
   (0.013514234, '카페'),
   (0.008143415, '바다'),
   (0.00782284, '아기'),
   (0.006860537, '식당'),
   (0.005806196, '메뉴'),
   (0.004532959, '사람'),
   (0.004462665, '돼지'),
   (0.004381956, '해변'),
   (0.0039979024, '커피'),
   (0.003917966, '애월'),
   (0.003868753, '서귀포'),
   (0.0037319597, '해수욕장'),
   (0.003650208, '가족'),
   (0.0035783183, '위치'),
   (0.0035232257, '음식'),
   (0.003452948, '칼국수'),
   (0.0033902784, '전복'),
   (0.0032577247, '바람'),
   (0.0032399478, '주차장')],
  -1.667538551043053),
 ([(0.017473347, '오름'),
   (0.015308348, '코스'),
   (0.012031718, '올레길'),
   (0.009560184, '사람'),
   (0.007035185, '한라산'),
   (0.005773244, '숲길'),
   (0.0050093043, '마을'),
   (0.0049544307, '풍경'),
   (0.004905106, '캠프'),
   (0.0042123124, '정상'),
   (0.0038352355, '겨울'),
   (0.0035315522, '걷기'),
   (0.0034288361, '식사'),
   (0.0033638703, '바다'),
   (0.0033582097, '사려'),
   (0.0033447628, '올레'),
   (0.0033435742, '해변'),
   (0.003272243, '버스'),
   (0.003267819, '둘레길'),
   (0.0032384875, '나무')],
  -1.698734366700705),
 ([(0.015044305, '카페'),
   (0.011088425, '바다'),
   (0.010433327, '사람'),
   (0.006373038, '날씨'),
   (0.005515511, '체험'),
   (0.0049265996, '해수욕장'),
   (0.004696184, '구경'),
   (0.004004708, '친구'),
   (0.0039984616, '우도'),
   (0.003354284, '바람'),
   (0.0032112196, '커피'),
   (0.0030991668, '비행기'),
   (0.0030004357, '산책'),
   (0.002906156, '노을'),
   (0.0027766924, '공항'),
   (0.0027105568, '맛집'),
   (0.0025044754, '남편'),
   (0.0024683748, '함덕'),
   (0.0024520217, '주차'),
   (0.002379647, '기록')],
  -1.7352049228874917),
 ([(0.011180566, '바다'),
   (0.009738998, '사람'),
   (0.0063769394, '친구'),
   (0.0051034214, '가족'),
   (0.0047974223, '벚꽃'),
   (0.0047779717, '카페'),
   (0.004290761, '거리'),
   (0.0041313316, '해변'),
   (0.0039883447, '생활'),
   (0.0037949192, '날씨'),
   (0.0035247141, '풍경'),
   (0.003305284, '요리'),
   (0.0030666387, '위치'),
   (0.0030464276, '우동'),
   (0.003039948, '분위기'),
   (0.0029921622, '게스트'),
   (0.0028946747, '손님'),
   (0.0028001524, '마당'),
   (0.0027998353, '식사'),
   (0.0027978693, '고기')],
  -1.8528494601017524),
 ([(0.0093182605, '하우스'),
   (0.008316321, '위치'),
   (0.005785477, '가족'),
   (0.005334788, '서귀포'),
   (0.0053282636, '시설'),
   (0.005209361, '바다'),
   (0.0047216937, '거리'),
   (0.004484927, '마당'),
   (0.003929376, '감성'),
   (0.0035557684, '분위기'),
   (0.0034455664, '쉐어'),
   (0.0034152826, '테라스'),
   (0.0032330353, '테이블'),
   (0.0031899628, '주차'),
   (0.0030589327, '빨래'),
   (0.0029270072, '애월'),
   (0.0029252616, '힐링'),
   (0.002911793, '내부'),
   (0.002905933, '주변'),
   (0.0028916395, '민박')],
  -1.9482858649298922)]

In [16]:
df_topic = pd.DataFrame(model.print_topics())
df_topic.columns = ['group', 'topic']
df_topic

   group                                              topic
0      0  0.011*"바다" + 0.010*"사람" + 0.006*"친구" + 0.005*"...
1      1  0.017*"오름" + 0.015*"코스" + 0.012*"올레길" + 0.010*...
2      2  0.009*"하우스" + 0.008*"위치" + 0.006*"가족" + 0.005*...
3      3  0.015*"카페" + 0.011*"바다" + 0.010*"사람" + 0.006*"...
4      4  0.015*"맛집" + 0.014*"카페" + 0.008*"바다" + 0.008*"...

In [17]:
temp = df_topic['topic'].str.split('+', expand=True)
for i in range(10):    
    temp.rename(columns= {i: f'topic_{i}'}, inplace= True)
    temp[[f'topic_{i}_rate', f'topic_{i}_key']] = temp[f'topic_{i}'].str.split('*', expand=True)
    temp.drop(columns= f'topic_{i}', inplace=True)
    temp[f'topic_{i}_key'] = temp[f'topic_{i}_key'].apply(lambda x: x.replace('"', ''))
    
temp.reset_index(inplace=True)
temp.rename(columns={'index' : 'group'}, inplace=True)
temp

,group,topic_0_rate,topic_0_key,topic_1_rate,topic_1_key,topic_2_rate,topic_2_key,topic_3_rate,topic_3_key,topic_4_rate,...,topic_5_rate,topic_5_key,topic_6_rate,topic_6_key,topic_7_rate,topic_7_key,topic_8_rate,topic_8_key,topic_9_rate,topic_9_key
0,0,0.011,바다,0.010,사람,0.006,친구,0.005,가족,0.005,...,0.005,카페,0.004,거리,0.004,해변,0.004,생활,0.004,날씨
1,1,0.017,오름,0.015,코스,0.012,올레길,0.010,사람,0.007,...,0.006,숲길,0.005,마을,0.005,풍경,0.005,캠프,0.004,정상
2,2,0.009,하우스,0.008,위치,0.006,가족,0.005,서귀포,0.005,...,0.005,바다,0.005,거리,0.004,마당,0.004,감성,0.004,분위기
3,3,0.015,카페,0.011,바다,0.010,사람,0.006,날씨,0.006,...,0.005,해수욕장,0.005,구경,0.004,친구,0.004,우도,0.003,바람
4,4,0.015,맛집,0.014,카페,0.008,바다,0.008,아기,0.007,...,0.006,메뉴,0.005,사람,0.004,돼지,0.004,해변,0.004,커피