In [1]:
import pandas as pd
import numpy as np
import requests, json
from urllib.parse import quote

# geo info를 획득하기 위해 데이터 준비

- 원래 계획은 행안부 api로 주소를 획득하고, 카카오 api로 좌표를 얻고자 함
- 하지만 행안부 api 검색시 주소 검색 오류 발생
----------------------------
- 국토교통부 레일포털에 기차역 정보에 관한 api 확인
- 이를 통해서 기차역 정보 획득하고자 함
-> api에서는 도시철도 기차역 정보만 존재
---------------------------
- 국토교통부 레일포털에서 크롤링을 통해
- 기차역 주소 확인 
- SR 단독 기차역(ex - 수서, 동탄) 및 일부역 확인불가
---------------------------
### <strong>최종방안</strong>
1. 크롤링 정보는 기반으로 주소 정보 획득
2. 없는 주소는 행안부 api로
3. 마지막은 직접 검색으로 - 다행이 없었다

In [2]:
train = pd.read_csv('./train.csv')
df = train.copy()
df.head(2)

,station,down_on_2016,down_off_2016,down_total_2016,down_kilo_2016,up_on_2016,up_off_2016,up_total_2016,up_kilo_2016,total_2016,...,on_ktx_2022,on_saemaul_2022,on_mugungwha_2022,on_commute_2022,on_total_2022,off_ktx_2022,off_saemaul_2022,off_mugungwha_2022,off_commute_2022,off_total_2022
0,각계,0.0,0.0,0.0,0.0,475.0,6.0,481.0,640.0,481.0,...,0.0,0.0,372.0,0.0,372.0,0.0,0.0,16.0,0.0,16.0
1,강경,29781.0,114890.0,144671.0,15222925.0,114280.0,33367.0,147647.0,6863592.0,292318.0,...,0.0,13357.0,91522.0,0.0,104879.0,0.0,18820.0,86335.0,0.0,105155.0

In [3]:
# 주소를 확인하고, 좌표를 획득하기 위해서 역 이름에 역 추가
addr = df.loc[:, 'station'].to_frame()
addr['station2'] = addr['station'].apply(lambda x: str(x) + '역')
addr.head(2)

  station station2
0      각계      각계역
1      강경      강경역

### step1 : 국토교통부 레일포털을 통해 geo info 획득 - 크롤링

- 총 215개의 역
- 1번째 페이지 - https://www.kric.go.kr/jsp/board/portal/sub05/est/estationList.jsp?pageNo=1
- 마지막 페이지 -https://www.kric.go.kr/jsp/board/portal/sub05/est/estationList.jsp?pageNo=22
- SR 운영역 및 일부역 검색안됨
-

In [4]:
import requests
from bs4 import BeautifulSoup

In [5]:
test_url = 'https://www.kric.go.kr/jsp/board/portal/sub05/est/estationList.jsp?pageNo=1'
resp = requests.get(test_url)
html = resp.text
soup = BeautifulSoup(html, 'html.parser')
# soup

In [6]:
soup.select('.bd_railway_station')

[<col class="bd_railway_station"/>,
 <th class="bd_railway_station" scope="col">역명</th>,
 <td class="bd_railway_station left"><a href="javascript:popDetail('A030280313')" title="새 창으로 열림">서울역</a></td>,
 <td class="bd_railway_station left"><a href="javascript:popDetail('A030280478')" title="새 창으로 열림">용산역</a></td>,
 <td class="bd_railway_station left"><a href="javascript:popDetail('A030280435')" title="새 창으로 열림">영등포역</a></td>,
 <td class="bd_railway_station left"><a href="javascript:popDetail('A030280054')" title="새 창으로 열림">광명역</a></td>,
 <td class="bd_railway_station left"><a href="javascript:popDetail('A030280607')" title="새 창으로 열림">청량리역</a></td>,
 <td class="bd_railway_station left"><a href="javascript:popDetail('A030280400')" title="새 창으로 열림">안양역</a></td>,
 <td class="bd_railway_station left"><a href="javascript:popDetail('A030280700')" title="새 창으로 열림">상봉역</a></td>,
 <td class="bd_railway_station left"><a href="javascript:popDetail('A030280355')" title="새 창으로 열림">수원역</a></td>,
 <td class="bd_railway_station left"><a href="javascript:popDetail('A030280450')" title="새 창으로 열림">오산역</a></td>,
 <td class="bd_railway_station left"><a href="javascript:popDetail('A030280314')" title="새 창으로 열림">서정리역</a></td>]

In [7]:
soup.select('.bd_railway_station')[2].text

'서울역'

In [8]:
soup.select('.bd_railway_add')

[<col class="bd_railway_add"/>,
 <th class="bd_railway_add" scope="col">주소</th>,
 <td class="bd_railway_add left">서울시 중구 한강대로 405</td>,
 <td class="bd_railway_add left">서울특별시 용산구 한강대로 23길 55</td>,
 <td class="bd_railway_add left">서울특별시 영등포구 경인로 846</td>,
 <td class="bd_railway_add left">경기도 광명시 광명역로 21</td>,
 <td class="bd_railway_add left">서울특별시 동대문구 왕산로 214</td>,
 <td class="bd_railway_add left">경기도 안양시 만안구 만안로 244</td>,
 <td class="bd_railway_add left">서울특별시 중랑구 망우로 297</td>,
 <td class="bd_railway_add left">경기도 수원시 팔달구 덕영대로 924 </td>,
 <td class="bd_railway_add left">경기도 오산시 오산동 역광장로 59</td>,
 <td class="bd_railway_add left">경기도 평택시 탄현로 51</td>]

In [9]:
soup.select('.bd_railway_add')[2].text

'서울시 중구 한강대로 405'

In [10]:
# temp = pd.DataFrame()
# station = []
# road_addr = []
# for i in range(2, 12):
#     url = 'https://www.kric.go.kr/jsp/board/portal/sub05/est/estationList.jsp?pageNo=1'
#     resp = requests.get(url)
#     html = resp.text
#     soup = BeautifulSoup(html, 'html.parser')
#     station_name = soup.select('.bd_railway_station')[i].text
#     station_roadaddr = soup.select('.bd_railway_add')[i].text
#     station.append(station_name)
#     road_addr.append(station_roadaddr)

# temp['station'] = station
# temp['road_addr'] = road_addr
# temp

In [11]:
temp = pd.DataFrame()
station = []
road_addr = []
for i in range(1, 23):
    if i < 22 :
        for j in range(2, 12):
            url = f'https://www.kric.go.kr/jsp/board/portal/sub05/est/estationList.jsp?pageNo={i}'
            resp = requests.get(url)
            html = resp.text
            soup = BeautifulSoup(html, 'html.parser')
            station_name = soup.select('.bd_railway_station')[j].text
            station_roadaddr = soup.select('.bd_railway_add')[j].text
            station.append(station_name)
            road_addr.append(station_roadaddr)
    # 22page는 5개역만 존재
    else :
        for j in range(2, 7):
            url = f'https://www.kric.go.kr/jsp/board/portal/sub05/est/estationList.jsp?pageNo={i}'
            resp = requests.get(url)
            html = resp.text
            soup = BeautifulSoup(html, 'html.parser')
            station_name = soup.select('.bd_railway_station')[j].text
            station_roadaddr = soup.select('.bd_railway_add')[j].text
            station.append(station_name)
            road_addr.append(station_roadaddr)
        

temp['station2'] = station
temp['road_addr'] = road_addr
temp

     station2               road_addr
0         서울역         서울시 중구 한강대로 405
1         용산역   서울특별시 용산구 한강대로 23길 55
2        영등포역      서울특별시 영등포구 경인로 846
3         광명역         경기도 광명시 광명역로 21
4        청량리역      서울특별시 동대문구 왕산로 214
..        ...                     ...
210    김천(구미)     경상북도 김천시 남면 혁신1로 51
211       둔내역  강원도 횡성군 둔내면 자포곡리 429-1
212       센텀역     부산광역시 해운대구 해운대로 210
213      서원주역         강원도 원주시 지정로 145
214  양원(영동선)역  경상북도 봉화군 소천면 분천리 113-2

[215 rows x 2 columns]

In [12]:
temp['station2'].unique()

array(['서울역', '용산역', '영등포역', '광명역', '청량리역', '안양역', '상봉역', '수원역', '오산역',
       '서정리역', '평택역', '성환역', '한림정역', '천안역', '전의역', '조치원역', '부강역', '신탄진역',
       '진영역', '오송역', '청주역', '천안아산역', '대전역', '오근장역', '청주공항역', '증평역', '옥천역',
       '이원역', '지탄역', '심천역', '영동역', '음성역', '황간역', '주덕역', '추풍령역', '진례역',
       '덕소역', '충주역', '김천역', '옥산역', '청리역', '상주역', '삼탄역', '구미역', '약목역',
       '왜관역', '신동역', '창원중앙역', '서대전역', '대구역', '동대구역', '경산역', '함창역', '행신역',
       '남성현역', '하양역', '청도역', '상동역', '창원역', '밀양역', '점촌역', '신경주역', '삼랑진역',
       '원동역', '물금역', '화명역', '구포역', '사상역', '부전역', '울산역', '마산역', '개포역',
       '아산역', '용궁역', '계룡역', '예천역', '중리역', '함안역', '기장역', '온양온천역', '군북역',
       '좌천역', '연산역', '논산역', '도고온천역', '신례원역', '남창역', '양평역', '덕하역', '강경역',
       '예산역', '반성역', '함열역', '태화강역', '삽교역', '용문역', '지평역', '석불역', '일신역',
       '호계역', '매곡역', '홍성역', '양동역', '삼산역', '불국사역', '진주역', '만종역', '완사역',
       '광천역', '북천역', '안강역', '청소역', '원주역', '극락강역', '횡천역', '부산역', '대천역',
       '하동역', '진상역', '광양역', '웅천역', '봉양역', '판교역', '제천역', '서천역', '장항역',
       '군산역', '단양역', '광주역', '포항역', '풍기역', '쌍용역', '영주역', '영월역', '봉화역',
       '예미역', '민둥산역', '춘양역', '사북역', '안동역', '고한역', '임기역', '현동역', '분천역',
       '태백역', '의성역', '승부역', '석포역', '탑리역', '대야역', '철암역', '화본역', '동백산역',
       '신녕역', '익산역', '김제역', '북영천역', '삼례역', '도계역', '신태인역', '영천역', '정읍역',
       '전주역', '건천역', '백양사역', '신기역', '서경주역', '임실역', '장성역', '동해역', '경주역',
       '오수역', '묵호역', '남원역', '정동진역', '곡성역', '구례구역', '순천역', '벌교역', '조성역',
       '예당역', '여천역', '득량역', '여수엑스포역', '보성역', '명봉역', '이양역', '능주역', '화순역',
       '효천역', '서광주역', '광주송정역', '나주역', '다시역', '함평역', '무안역', '몽탄역', '일로역',
       '임성리역', '목포역', '강릉역', '공주역', '신해운대역', '월포역', '평창역', '횡성역',
       '진부(오대산)역', '장사역', '영덕역', '강구역', '김천(구미)', '둔내역', '센텀역', '서원주역',
       '양원(영동선)역'], dtype=object)

In [13]:
# 이름에 예외가 있는 역들 수정
temp['station2'] = temp['station2'].str.replace('김천(구미)','김천구미역')
temp['station2'] = temp['station2'].str.replace('진부(오대산)역','진부역')
temp['station2'] = temp['station2'].str.replace('양원(영동선)역','양원역')
temp['station2']

0        서울역
1        용산역
2       영등포역
3        광명역
4       청량리역
       ...
210    김천구미역
211      둔내역
212      센텀역
213     서원주역
214      양원역
Name: station2, Length: 215, dtype: object

In [14]:
temp['station2'].unique()

array(['서울역', '용산역', '영등포역', '광명역', '청량리역', '안양역', '상봉역', '수원역', '오산역',
       '서정리역', '평택역', '성환역', '한림정역', '천안역', '전의역', '조치원역', '부강역', '신탄진역',
       '진영역', '오송역', '청주역', '천안아산역', '대전역', '오근장역', '청주공항역', '증평역', '옥천역',
       '이원역', '지탄역', '심천역', '영동역', '음성역', '황간역', '주덕역', '추풍령역', '진례역',
       '덕소역', '충주역', '김천역', '옥산역', '청리역', '상주역', '삼탄역', '구미역', '약목역',
       '왜관역', '신동역', '창원중앙역', '서대전역', '대구역', '동대구역', '경산역', '함창역', '행신역',
       '남성현역', '하양역', '청도역', '상동역', '창원역', '밀양역', '점촌역', '신경주역', '삼랑진역',
       '원동역', '물금역', '화명역', '구포역', '사상역', '부전역', '울산역', '마산역', '개포역',
       '아산역', '용궁역', '계룡역', '예천역', '중리역', '함안역', '기장역', '온양온천역', '군북역',
       '좌천역', '연산역', '논산역', '도고온천역', '신례원역', '남창역', '양평역', '덕하역', '강경역',
       '예산역', '반성역', '함열역', '태화강역', '삽교역', '용문역', '지평역', '석불역', '일신역',
       '호계역', '매곡역', '홍성역', '양동역', '삼산역', '불국사역', '진주역', '만종역', '완사역',
       '광천역', '북천역', '안강역', '청소역', '원주역', '극락강역', '횡천역', '부산역', '대천역',
       '하동역', '진상역', '광양역', '웅천역', '봉양역', '판교역', '제천역', '서천역', '장항역',
       '군산역', '단양역', '광주역', '포항역', '풍기역', '쌍용역', '영주역', '영월역', '봉화역',
       '예미역', '민둥산역', '춘양역', '사북역', '안동역', '고한역', '임기역', '현동역', '분천역',
       '태백역', '의성역', '승부역', '석포역', '탑리역', '대야역', '철암역', '화본역', '동백산역',
       '신녕역', '익산역', '김제역', '북영천역', '삼례역', '도계역', '신태인역', '영천역', '정읍역',
       '전주역', '건천역', '백양사역', '신기역', '서경주역', '임실역', '장성역', '동해역', '경주역',
       '오수역', '묵호역', '남원역', '정동진역', '곡성역', '구례구역', '순천역', '벌교역', '조성역',
       '예당역', '여천역', '득량역', '여수엑스포역', '보성역', '명봉역', '이양역', '능주역', '화순역',
       '효천역', '서광주역', '광주송정역', '나주역', '다시역', '함평역', '무안역', '몽탄역', '일로역',
       '임성리역', '목포역', '강릉역', '공주역', '신해운대역', '월포역', '평창역', '횡성역', '진부역',
       '장사역', '영덕역', '강구역', '김천구미역', '둔내역', '센텀역', '서원주역', '양원역'],
      dtype=object)

In [15]:
addr = pd.merge(addr, temp,
         how = 'left',
         on = 'station2')
addr

    station station2              road_addr
0        각계      각계역                    NaN
1        강경      강경역    충청남도 논산시 강경읍 대흥로 1
2        개포      개포역  경상북도 예천군 개포면 방터길 7-11
3        경산      경산역         경상북도 경산시 중앙로 1
4        경주      경주역       경상북도 경주시 원화로 266
..      ...      ...                    ...
191      익산      익산역      전라북도 익산시 익산대로 153
192      정읍      정읍역    전라북도 정읍시 서부산업도로 305
193      부산      부산역      부산광역시 동구 중앙대로 206
194      대전      대전역       대전광역시 동구 중앙로 215
195    천안아산    천안아산역  충청남도 아산시 배방읍 희망로 100

[196 rows x 3 columns]

In [16]:
addr[addr['road_addr'].isna() == True]

    station station2 road_addr
0        각계      각계역       NaN
20       나전      나전역       NaN
48      별어곡     별어곡역       NaN
56       비동      비동역       NaN
71       선평      선평역       NaN
84     아우라지    아우라지역       NaN
131      정선      정선역       NaN
180      수서      수서역       NaN
181      동탄      동탄역       NaN

In [17]:
addr.rename(columns = {'road_addr' : 'road_addr1'}, inplace = True)
addr

    station station2             road_addr1
0        각계      각계역                    NaN
1        강경      강경역    충청남도 논산시 강경읍 대흥로 1
2        개포      개포역  경상북도 예천군 개포면 방터길 7-11
3        경산      경산역         경상북도 경산시 중앙로 1
4        경주      경주역       경상북도 경주시 원화로 266
..      ...      ...                    ...
191      익산      익산역      전라북도 익산시 익산대로 153
192      정읍      정읍역    전라북도 정읍시 서부산업도로 305
193      부산      부산역      부산광역시 동구 중앙대로 206
194      대전      대전역       대전광역시 동구 중앙로 215
195    천안아산    천안아산역  충청남도 아산시 배방읍 희망로 100

[196 rows x 3 columns]

### step2 - 주소값이 나오지 않은 역의 도로명 주소를 넣기
#### 행정안전부 api를 통해 기차역의 주소 획득
- 해당 api의 문제
    1. 서울역 주소검색시 - 서울역풍림아이원 플러스 주소가 얻어진다.
    2. 주소가 나오지 않는 기차역 존재 - 논산역 등
 
-------------
-> 크롤링을 통해 얻지 못한 일부 역들만 활용한다.

In [18]:
with open('D:/song/class_appendix/key/도로명주소api키.txt') as file:
    addr_key = file.read()

In [19]:
quote('수서역')

'%EC%88%98%EC%84%9C%EC%97%AD'

In [20]:
base_url = 'https://www.juso.go.kr/addrlink/addrLinkApi.do'
params1 = f'confmKey={addr_key}&currentPage=1&countPerPage=10'
params2 = f'keyword={quote("수서역")}&resultType=json'
url = f'{base_url}?{params1}&{params2}'

In [21]:
result = requests.get(url)
result.status_code

200

In [22]:
# result.json()['results'].keys()
result.json()['results']['juso'][0]['roadAddr']

'서울특별시 강남구 광평로 지하270 (수서동)'

In [23]:
import time

def find_addr(station_name):
    base_url = 'https://www.juso.go.kr/addrlink/addrLinkApi.do'
    params1 = f'confmKey={addr_key}&currentPage=1&countPerPage=10'
    params2 = f'keyword={quote(station_name)}&resultType=json'
    url = f'{base_url}?{params1}&{params2}'
    result = requests.get(url)
    try:
        if result.status_code == 200:
            res = json.loads(result.text)
            return result.json()['results']['juso'][0]['roadAddr']
        else :
            return 'none'
    except:
        return 'what'
    time.sleep(0.3)

In [24]:
addr['road_addr2'] = addr['station2'].apply(lambda x: find_addr(x))

In [25]:
addr['road_addr'] = addr.apply(lambda x: x['road_addr1'] if not pd.isna(x['road_addr1']) else x['road_addr2'], axis=1)
addr

,station,station2,road_addr1,road_addr2,road_addr
0,각계,각계역,NaN,충청북도 영동군 심천면 각계길 55,충청북도 영동군 심천면 각계길 55
1,강경,강경역,충청남도 논산시 강경읍 대흥로 1,충청남도 논산시 강경읍 대흥로 1,충청남도 논산시 강경읍 대흥로 1
2,개포,개포역,경상북도 예천군 개포면 방터길 7-11,경상북도 예천군 개포면 방터길 7-11,경상북도 예천군 개포면 방터길 7-11
3,경산,경산역,경상북도 경산시 중앙로 1,경상북도 경산시 중앙로 1 (사정동),경상북도 경산시 중앙로 1
4,경주,경주역,경상북도 경주시 원화로 266,경상북도 경주시 건천읍 경주역세권4로 24,경상북도 경주시 원화로 266
...,...,...,...,...,...
191,익산,익산역,전라북도 익산시 익산대로 153,전라북도 익산시 익산대로 153 (창인동2가),전라북도 익산시 익산대로 153
192,정읍,정읍역,전라북도 정읍시 서부산업도로 305,전라북도 정읍시 서부산업도로 305 (연지동),전라북도 정읍시 서부산업도로 305
193,부산,부산역,부산광역시 동구 중앙대로 206,부산광역시 동구 중앙대로179번길 27 (초량동),부산광역시 동구 중앙대로 206
194,대전,대전역,대전광역시 동구 중앙로 215,대전광역시 동구 역전시장길 7 (정동),대전광역시 동구 중앙로 215
195,천안아산,천안아산역,충청남도 아산시 배방읍 희망로 100,충청남도 아산시 배방읍 연화로 99,충청남도 아산시 배방읍 희망로 100

In [26]:
addr[addr['road_addr'].isna() == True]

Empty DataFrame
Columns: [station, station2, road_addr1, road_addr2, road_addr]
Index: []

In [27]:
addr = addr[['station', 'road_addr']]
addr

    station              road_addr
0        각계    충청북도 영동군 심천면 각계길 55
1        강경    충청남도 논산시 강경읍 대흥로 1
2        개포  경상북도 예천군 개포면 방터길 7-11
3        경산         경상북도 경산시 중앙로 1
4        경주       경상북도 경주시 원화로 266
..      ...                    ...
191      익산      전라북도 익산시 익산대로 153
192      정읍    전라북도 정읍시 서부산업도로 305
193      부산      부산광역시 동구 중앙대로 206
194      대전       대전광역시 동구 중앙로 215
195    천안아산  충청남도 아산시 배방읍 희망로 100

[196 rows x 2 columns]

In [28]:
addr.loc[:, 'city2'] = addr['road_addr'].apply(lambda x: x.split()[0] + " " + x.split()[1] 
                                             if isinstance(x, str) and len(x.split()) > 2 else None)

C:\Users\dotho\AppData\Local\Temp\ipykernel_7800\141223876.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  addr.loc[:, 'city2'] = addr['road_addr'].apply(lambda x: x.split()[0] + " " + x.split()[1]

In [29]:
addr

    station              road_addr     city2
0        각계    충청북도 영동군 심천면 각계길 55  충청북도 영동군
1        강경    충청남도 논산시 강경읍 대흥로 1   충청남도 논산시
2        개포  경상북도 예천군 개포면 방터길 7-11  경상북도 예천군
3        경산         경상북도 경산시 중앙로 1  경상북도 경산시
4        경주       경상북도 경주시 원화로 266  경상북도 경주시
..      ...                    ...       ...
191      익산      전라북도 익산시 익산대로 153  전라북도 익산시
192      정읍    전라북도 정읍시 서부산업도로 305  전라북도 정읍시
193      부산      부산광역시 동구 중앙대로 206  부산광역시 동구
194      대전       대전광역시 동구 중앙로 215  대전광역시 동구
195    천안아산  충청남도 아산시 배방읍 희망로 100   충청남도 아산시

[196 rows x 3 columns]

### step3 - KAKAO api로 좌표 획득하기

In [30]:
# api 가져오기
with open('D:/song/class_appendix/key/kakao_map_key.txt') as file:
    kakao_key = file.read()

In [68]:
# https://developers.kakao.com/docs/latest/ko/local/dev-guide#address-coord
base_url = 'https://dapi.kakao.com/v2/local/search/address.json'
addr_test = '서울특별시 서대문구 신촌역로 4 (대현동)'
url = f'{base_url}?query={quote(addr_test)}'
# header : Authorization: KakaoAK ${REST_API_KEY}
header = {'Authorization': f'KakaoAK {kakao_key}'}

In [71]:
result = requests.get(url, headers = header).json()
result

{'documents': [{'address': {'address_name': '서울 서대문구 대현동 101-22',
    'b_code': '1141011200',
    'h_code': '1141058500',
    'main_address_no': '101',
    'mountain_yn': 'N',
    'region_1depth_name': '서울',
    'region_2depth_name': '서대문구',
    'region_3depth_h_name': '신촌동',
    'region_3depth_name': '대현동',
    'sub_address_no': '22',
    'x': '126.94311045086',
    'y': '37.5571114864975'},
   'address_name': '서울 서대문구 신촌역로 4',
   'address_type': 'ROAD_ADDR',
   'road_address': {'address_name': '서울 서대문구 신촌역로 4',
    'building_name': '',
    'main_building_no': '4',
    'region_1depth_name': '서울',
    'region_2depth_name': '서대문구',
    'region_3depth_name': '대현동',
    'road_name': '신촌역로',
    'sub_building_no': '',
    'underground_yn': 'N',
    'x': '126.94311045086',
    'y': '37.5571114864975',
    'zone_no': '03766'},
   'x': '126.94311045086',
   'y': '37.5571114864975'}],
 'meta': {'is_end': True, 'pageable_count': 1, 'total_count': 1}}

In [33]:
result['documents'][0]['address']['x'] #lon

'126.94311045086'

In [34]:
result['documents'][0]['address']['y'] #lat

'37.5571114864975'

In [73]:
def kakao_api_lat(road_addr):
    base_url = 'https://dapi.kakao.com/v2/local/search/address.json'
    addr_input = road_addr
    url = f'{base_url}?query={quote(addr_input)}'
    header = {'Authorization': f'KakaoAK {kakao_key}'}
    result = requests.get(url, headers = header).json()
    try:
        return result['documents'][0]['address']['y']
        
    except:
        return 'what'
    time.sleep(0.3)

In [74]:
def kakao_api_lon(road_addr):
    base_url = 'https://dapi.kakao.com/v2/local/search/address.json'
    addr_input = road_addr
    url = f'{base_url}?query={quote(addr_input)}'
    header = {'Authorization': f'KakaoAK {kakao_key}'}
    result = requests.get(url, headers = header).json()
    try:
        return result['documents'][0]['address']['x']
        
    except:
        return 'what'
    time.sleep(0.3)

In [77]:
addr['lat'] = addr['road_addr'].apply(lambda x: kakao_api_lat(x))
addr['lon'] = addr['road_addr'].apply(lambda x: kakao_api_lon(x))
addr

,station,road_addr,city2,lat,lon
0,각계,충청북도 영동군 심천면 각계길 55,충청북도 영동군,36.2082391901684,127.725461390372
1,강경,충청남도 논산시 강경읍 대흥로 1,충청남도 논산시,36.1540371773264,127.015227693571
2,개포,경상북도 예천군 개포면 방터길 7-11,경상북도 예천군,36.6269985085784,128.328886875692
3,경산,경상북도 경산시 중앙로 1,경상북도 경산시,35.8193911083973,128.727508240274
4,경주,경상북도 경주시 원화로 266,경상북도 경주시,35.8473612313022,129.218053667485
...,...,...,...,...,...
191,익산,전라북도 익산시 익산대로 153,전라북도 익산시,35.9418527931554,126.947304569201
192,정읍,전라북도 정읍시 서부산업도로 305,전라북도 정읍시,35.5756468360555,126.842502480741
193,부산,부산광역시 동구 중앙대로 206,부산광역시 동구,35.117605126596,129.045060216345
194,대전,대전광역시 동구 중앙로 215,대전광역시 동구,36.3344230194263,127.432103833008
195,천안아산,충청남도 아산시 배방읍 희망로 100,충청남도 아산시,36.7945268974723,127.104450472765

# step4 - 마무리